AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  FacebookGateway:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: facebook-gateway.handler
      Runtime: python2.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::213438495744:role/service-role/lambda-messenger-bot-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /Facebook-Gateway
            Method: ANY
